"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var celular_1 = require("./celular");
var cel1 = new celular_1.Celular("Samsung", "Galaxy S24", "Android", 8, 256, false);
var cel2 = new celular_1.Celular("Motorola", "E02", "Android", 1);
var cel3 = new celular_1.Celular("Iphone", "16 Pro", "iOS", undefined, 1024, true);
var cel4 = new celular_1.Celular("Xiao", "Note 10 Pro", "Android");
console.log("Marca del Cel 1: ".concat(cel1.getBrand()));
console.log("\nInfo del Cel 2:");
console.log(cel2.showInfo());
cel3.setStorage(128);
console.log("\nAlmacenamiento del Cel 3: ".concat(cel3.getStorage()));
cel4.setBrand("Xiaomi");
cel4.onOff();
console.log("\nMarca del Cel 4 (corregida): ".concat(cel4.getBrand()));
console.log("\nEl Cel 4 est\u00E1 encendido? ".concat(cel4.isTurnedOn()));
console.log("\nInfo del Cel 3");
console.log(cel3.showInfo());
console.log("\nInfo del Cel 4");
console.log(cel4.showInfo());
