"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var escuela_1 = require("./escuela");
var curso_1 = require("./curso");
var alumno_1 = require("./alumno");
var docente_1 = require("./docente");
var cresta = new escuela_1.Escuela("CRESTA");
var juan = new alumno_1.Alumno("Juan", "Perez", new Date("1995-05-27"), 39725123);
var maria = new alumno_1.Alumno("Maria", "Suarez", new Date("1997-04-17"), 40373333);
var lucas = new alumno_1.Alumno("Lucas", "Gonzalez", new Date("1996-11-01"), 40002234);
var doc_Pablo = new docente_1.Docente("Pablo", "Demateo", new Date("1991-07-26"), 36364622, 1200);
var doc_Gimena = new docente_1.Docente("Gimena", "Corrales", new Date("1993-01-30"), 37855697, 1100);
cresta.agregarAlumno(juan);
cresta.agregarAlumno(maria);
cresta.agregarAlumno(lucas);
cresta.agregarDocente(doc_Gimena);
cresta.agregarDocente(doc_Pablo);
var cursoAlgebra = new curso_1.Curso("Algebra 1", 12, new Date("2025-08-5"), doc_Pablo);
var cursoIngles = new curso_1.Curso("Ingles 2", 8, new Date("2025-03-6"), doc_Gimena);
cresta.agregarCurso(cursoAlgebra);
cresta.agregarCurso(cursoIngles);
cursoAlgebra.agregarAlumnos([juan, maria]);
cursoIngles.agregarAlumnos([lucas]);
cresta.listarInfo();
